version: '3.4'

services:

  eureka-server:
    image: pauloultra/eureka-server:1.0.0
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - microsservices

  api-gateway:
    image: pauloultra/api-gateway:1.0.0
    ports:
      - "8765:8765"
    expose:
      - "8765"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - microsservices

  user-api:
    image: pauloultra/user-api:1.0.0
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - PORT=8001
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - microsservices

  payroll-api:
    image: pauloultra/payroll-api:1.0.0
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server
      - api-gateway
      - user-api
    environment:
      - PORT=8100
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - microsservices      

networks:
  microsservices:
    driver: bridge